apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: stock-market-app
spec:
  type: ClusterIP
  selector:
    app: stocks-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000