apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: stock-market-app
spec:
  type: ClusterIP
  selector:
    app: capital-gains-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080