apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: stock-market-app
spec:
  capacity:
    storage:  500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb
